[0m18:14:39.029589 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CAEFF8F9D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CAF1ECFF10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CAF1ECFFD0>]}


============================== 18:14:39.035334 | 5667e5e8-41c1-4e85-8a0c-af765b22bd7f ==============================
[0m18:14:39.035334 [info ] [MainThread]: Running with dbt=1.9.3
[0m18:14:39.036646 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\EMRando\\.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt init', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m18:15:07.283949 [debug] [MainThread]: Starter project path: c:\users\emrando\documents\internal\dbt jaffles\django-dash\django-dash\.venv\lib\site-packages\dbt\include\starter_project
[0m18:15:07.370157 [info ] [MainThread]: 
Your new dbt project "djaffle" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m18:15:07.370157 [info ] [MainThread]: Setting up your profile.
[0m18:15:11.144097 [debug] [MainThread]: Command `dbt init` succeeded at 18:15:11.144097 after 32.30 seconds
[0m18:15:11.144097 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CAEFF8F9D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CAF1ECFD30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CAF1E95C40>]}
[0m18:15:11.144097 [debug] [MainThread]: Flushing usage events
[0m18:15:11.787430 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m18:55:42.561138 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B49C30F9D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B49E252DF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B49E252FA0>]}


============================== 18:55:42.567193 | 58e5a55e-74f0-4b83-a156-f93863e51b39 ==============================
[0m18:55:42.567193 [info ] [MainThread]: Running with dbt=1.9.3
[0m18:55:42.569209 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': '.', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt compile --select board_products --profiles-dir .', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m18:55:42.571224 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\EMRando\Documents\Internal\DBT jaffles\django-dash\django-dash\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m18:55:42.574046 [debug] [MainThread]: Command `dbt compile` failed at 18:55:42.574046 after 0.22 seconds
[0m18:55:42.574046 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B49C30F9D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B49E252FA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B49E252DC0>]}
[0m18:55:42.574046 [debug] [MainThread]: Flushing usage events
[0m18:55:43.067868 [debug] [MainThread]: An error was encountered while trying to flush usage events
